version: '3'
services:
  # The Web Server
  web:
    container_name: maintenance
    image: nginx
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
